### ISSUE TITLE
usb ring light

### ISSUE THREAD

**Issue by tinni123** [pibooth/pibooth-extra-lights#4]
hey i have your plugin working with gpio pin for flash which is fantastic but the lights i picked are to bright and now i wanna see if there is a way to use usb with the plugin as i have a usb ring light which would be perfect but its usb and your plugin uses gpio pins any ideas ? cheers tinni

**Comment by satcomjimmy** [comment]
I am working on similar, but I am using an LED strip that needs 5v, so I am planning on using a GPIO pin to trigger a relay to send the 5v and bring up the LED strip. I may also try a transistor, based on this project: https://projects.raspberrypi.org/en/projects/balloon-pi-tay-popper/6

**Comment by anxuae** [comment]
Hi @tinni123 ,

As proposed by @satcomjimmy , you could use a relay in order to drive another device. Another solution could be to develop your own plugin, you can find some examples here: https://pibooth.readthedocs.io/en/latest/sources/plugins/examples.html

Also have a look to existing plugins, for instance https://pypi.org/project/pibooth-flashled/
