### ISSUE TITLE
Flash Don't Work

### ISSUE THREAD

**Issue by Taco5656** [pibooth/pibooth-extra-lights#6]
Hello,

I am a beginner

I installed Pibooth 2.07 on my raspberry pi 3 with Buster and I mounted a 220v to 12v converter to put a GU5.3 LED as a flash with a 5v relay module.
I encounter a problem with the flash when taking a capture with the "extra-light" plugin. When launching pibooth and the "extra-light" script, the flash shutdown, but during the shooting sequence, the flash does not work.

Here is my setup.
[Schema Flash.pdf](https://github.com/pibooth/pibooth/files/11424689/Schema.Flash.pdf)

I have correctly configured the correct pin 33 in the config file.

Where can my mistake come from?

Thanks for your help.

**Environment**
 - OS [Raspbian Buster]
 - Camera [Raspberry Camera v2]
 - Pibooth version [2.0.7]

**Comment by anxuae** [comment]
Hi @Taco5656 

Can you give me your config file?

**Comment by Taco5656** [comment]
Hi @anxuae 

My config file:
[pibooth.txt](https://github.com/pibooth/pibooth-extra-lights/files/11444227/pibooth.txt)

It's a ".txt" file beause I can't upload ".cfg" file on Github

Thank you for your help !

**Comment by DJ-Dingo** [comment]
Hey @Taco5656 do you have an "original" 5v relay module ?. or one of those cheap copy´s. It sounds like you have one of the cheap ones. I use them myself an they work opposite. So if you normally would use NO "NO means normally-open contact", you should now use NC "NC means normally-closed contact" on the cheap relays.

This mean that you can make it work by swap around the light cable a little on your relay, so where it nomally would be off (NO), you set the light cables as "NC" on your relay for your 220v or 12v light. 

"This will also mean that, when Pibooth program is not running, the light will be "on" all the time".

It will be as "on, with the red light" on the relay when it is not being used by Pibooth. And then it will switch "off on the red led" on your relay an now actually turn on your (220v or 12V) light when used by pibooth, the relay switches off.  

Confussing but thats how the cheap relays work, and "pibooth_extra_lights" don´t have the option to switch high/low on the led pins. 

But if you don´t mind changing some things in the plugin code, you can make it work for the cheap relays, without changing the cables.. You can do this by switching  "on, to off", an "off, to on" in the code yourself. 

In the plugin on every "@pibooth.hookimpl" There is a line "app.led_" if you only need this for the flash light you can make a change in the def state_capture_enter to "off" so it says "app.led_flash.off()" and in the def state_capture_exit to app.led_flash.on(). Now you´re relay will get the high/low opposite on the Flash_Led pin, and now work as a normal original relay.

These needs to be opposite in on/off
-----------------------------------------
@pibooth.hookimpl
def state_capture_enter(app):
    """Ready to take a capture."""
    app.led_flash.on()


@pibooth.hookimpl
def state_capture_exit(app):
    """A capture has been taken."""
    app.led_flash.off()



@anxuae it would actually be nice if inside "pibooth_extra_lights", you had the options in the menu to switch between high and low on led in the menu "just by switching the on/off funktion opposite in the script", but the option has to be for every single LED  (Startup, Preview, Flash_led), since not every LED always need the use of a relay. That way it will also support these cheap china "opposite" relays. I do have this option in my own version, maybe i should do a Pull requests with it when i get back from vecation.


I'm actually also putting the finishing touches on a new USB light plugin that can handle this with cheap relays, and all sorts of other options with defferent light´s. The cool thing is that it will work via USB, and can handle everything from relays with normal light/LEDstrips and the cool addressable LED Strips/Matrix as Flash thrue the USB.  I am in my final testing, and things looks good so far.

**Comment by Taco5656** [comment]
Hello @DJ-Dingo,

Thank you for your answer.

The 5v relay module is a module purchased from an "rs-online" site.

I made the modification on my relay by changing the wires from NO to NC. The flash is on until pibooth is launched. Once pibooth launched the script turns off the flash but it does not turn on again when taking a photo.

I tried different solutions:
- pin change
- test in "preview_led_pin" or not in "flash_led_pin"

But it doesn't work. When I close pibooth, the flash turns on again.

I think this is the same problem encountered in issue #5

Did the state names in pibooth 2.0.7 change? What makes the plugin no longer work?

Thanks a lot for your help.

**Comment by DJ-Dingo** [comment]
@Taco5656 I don´t no if the state names has changed in 2.07 we have to ask @anxuae. I havent updated my selfiecam to pibooth 2.07 yet, but i use 2.07 in my test box, so i can test there when i get home from vecation. 
 
And yes my light is also turn on before pibooth starts and turn off when pibooth is running the script. that is normal with the cheap oppostie relays. thats why i made some changes in the code of the plugin.

Do you have the wire directly from the pi to your relay, or do you using an external  PullUp / PullDown Resistors from the Raspberry Pi to the relay.
https://grantwinney.com/using-pullup-and-pulldown-resistors-on-the-raspberry-pi/

Scroll down to "Fixing the Simple Circuit
Option 1: Adding a Pull-Down Resistor to the Breadboard"

I am using something like this for my buttons and relays in my setup, (i could not find my own picture/manual online, but this looks alot like it).. It will help getting anouf power to activate and deactivate  the pin on the relay. 

But if you search on the internet for RPI relay external pullup/down or ask Chat gbt, you can get more info about it. There are manuals out there, that explain.

**Comment by anxuae** [comment]
Hi @Taco5656 and @DJ-Dingo 

There is no change in the state name since a long time. So I guess that issue is coming from the hardware wiring.
However this is a good idea to add option in order to choose the normally-closed/ normally-open contact. For instance:

```
startup_led_active_high = True
preview_led_active_high = True
flash_led_active_high = True
```

**Comment by Taco5656** [comment]
Hello @DJ-Dingo and @anxuae,

I tried different solutions but without success.

I tried to make a very simple script to see if the problem did not come from my relay module. This works well using the GPIO function.

```python
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

relay_pin = 13
GPIO.setup(relay_pin, GPIO.OUT)

def activate_relay():
   GPIO.output(relay_pin, GPIO.LOW)

def deactivate_relay():
    GPIO.output(relay_pin, GPIO.HIGH)

activate_relay()
time.sleep(5)
deactivate_relay()

GPIO.cleanup()
```

I manage to trigger the flash during the desired time. In which script can I embed this into pibooth?

THANKS :)

**Comment by anxuae** [comment]
Hi @Taco5656 

pibooth uses `gpiozero` library which is based on `RPi.GPIO`. Looking deeper to your script, your relay is working inverted as describe by @DJ-Dingo. So you "deactivate relay" (I suppose you means open the circuit == flash is off), when you set the pin 33 to HIGHT. Is it right?

The following script is doing exactly what `pibooth-extra-lights` do. Can you test it?

```python
import time
from gpiozero import LED

led = LED("BOARD33")

def activate_relay():
    led.on()

def deactivate_relay():
    led.off()

activate_relay()
time.sleep(5)
deactivate_relay()
```

if you have same behavior than with pibooth: ouf.
In that case, try this script:

```python
import time
from gpiozero import LED

led = LED("BOARD33", active_high=False)

def activate_relay():
    led.on()

def deactivate_relay():
    led.off()

activate_relay()
time.sleep(5)
deactivate_relay()
```

**Comment by Taco5656** [comment]
Hi @anxuae,

Thank you for your help.

Yes in the script with GPIO, the trigger is reversed which is normal. I can simply change between NO and NC. What I especially want to understand is why I have no change of state on my relay.

I tried your two scripts and my relay turns on fine but does not turn off after 5 seconds.

I tried different scripts with LED, LEDBOARD and even with OutputDevice . Each time the relay triggers but does not return to its original state after the programmed time.sleep.

Only with the RPI.GPIO can I trigger the change of state as I want.

**Comment by Taco5656** [comment]
Hello @anxuae ,

It's good it works! :D

Indeed it was necessary to make a Pull-up assembly to make the relay module work with the LED function.

I also managed to get the extra_lights script to work without a pull-up by using a MOSFET module instead of my relay module.

Many thank you for your help and for all the work done on Pibooth!

Bye!
